=== vidalcarlos/day2/src/java/bugReportSchema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    
    <xs:element name="bug">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element ref="prioridade"/>
                <xs:element name="descricao" type="xs:string"/>
                <xs:element name="imagem" type="xs:string"/>
                <xs:element name="fechado" type="xs:boolean"/>
            </xs:sequence>
            
            
        </xs:complexType>
        <xs:key name="id" />
                                    
    </xs:element>
    <xs:element name="prioridade">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="critico"/>
                <xs:enumeration value="sugestao"/>
                <xs:enumeration value="outro"/>
                    
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="bugReport">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bug" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" />
        </xs:complexType>
    </xs:element>
                    
                    
        

</xs:schema>

=== vidalcarlos/day2/src/java/bugReports.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="bugReportStyle.xsl"?>

<bugReport 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="bugReportSchema.xsd">
    
    <bug id="1" createDate="2015-05-19">
        <user>Jose Fulano</user>
        <email>jfulano@marinha.pt</email>
        <prioridade>critico</prioridade>
        <descricao>aplicação demora muito no processo</descricao>
        <imagem>img1.png</imagem>
        <fechado>true</fechado>
    </bug>
     <bug id="2" createDate="2015-05-19">
        <user>Jose Artista</user>
        <email>jartista@marinha.pt</email>
        <prioridade>sugestao</prioridade>
        <descricao>aplicação falha intermitente</descricao>
        <imagem>img2.png</imagem>
        <fechado>false</fechado>
    </bug>
</bugReport>
